-- ================================================================
-- Step 2: Create Essential Tables
-- ================================================================
-- Run this script as VECTOR user on the target database
-- ================================================================

PROMPT Creating MY_BOOKS table...

CREATE TABLE my_books (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
               MINVALUE 1 MAXVALUE 9999999999999999999999999999 
               INCREMENT BY 1 START WITH 1 CACHE 20 
               NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL,
  file_name    VARCHAR2(900),
  file_size    NUMBER,
  file_type    VARCHAR2(100),
  file_content BLOB,
  created_on   TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CONSTRAINT pk_my_books_id PRIMARY KEY (id),
  CONSTRAINT uq_my_books_name_size UNIQUE (file_name, file_size)
) 
LOB (file_content) STORE AS SECUREFILE (
  ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING NOCOMPRESS KEEP_DUPLICATES
);

PROMPT MY_BOOKS table created.

PROMPT Creating DEMO_BOOKS table...

CREATE TABLE demo_books (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
               MINVALUE 1 MAXVALUE 9999999999999999999999999999 
               INCREMENT BY 1 START WITH 1 CACHE 20 
               NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL,
  file_name    VARCHAR2(900),
  file_size    NUMBER,
  file_type    VARCHAR2(100),
  file_content BLOB,
  PRIMARY KEY (id)
)
LOB (file_content) STORE AS SECUREFILE (
  ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING NOCOMPRESS KEEP_DUPLICATES
);

PROMPT DEMO_BOOKS table created.

PROMPT Creating VECTOR_STORE table...

CREATE TABLE vector_store (
  doc_id       NUMBER NOT NULL,
  embed_id     NUMBER,
  embed_data   VARCHAR2(4000),
  embed_vector VECTOR,
  CONSTRAINT fk_vector_store_mybooks 
    FOREIGN KEY (doc_id) REFERENCES my_books(id) ON DELETE CASCADE
)
VECTOR (embed_vector) STORE AS (
  CHUNK 8192 RETENTION MIN 1800
);

PROMPT VECTOR_STORE table created.

-- Display table structure
PROMPT
PROMPT ================================================================
PROMPT Table Summary:
PROMPT ================================================================
SELECT table_name, 
       num_rows,
       ROUND(bytes/1024/1024, 2) as size_mb
FROM user_tables t
LEFT JOIN user_segments s ON t.table_name = s.segment_name
WHERE table_name IN ('MY_BOOKS', 'DEMO_BOOKS', 'VECTOR_STORE')
ORDER BY table_name;

PROMPT
PROMPT ================================================================
PROMPT Tables created successfully!
PROMPT ================================================================
PROMPT
PROMPT Next step: Import ML models (see 03_import_ml_models.sql)
PROMPT ================================================================
