# ================================================================
# Unity Project Zipper
# ================================================================
# Creates a distributable zip file of a Unity project with only
# the essential files needed to run on another machine.
#
# Usage: .\zipUnity.ps1 -ProjectPath "C:\Path\To\UnityProject"
# ================================================================

param(
    [Parameter(Mandatory=$true)]
    [string]$ProjectPath,
    
    [Parameter(Mandatory=$false)]
    [string]$OutputPath = (Get-Location).Path
)

# Validate project path
if (-not (Test-Path $ProjectPath)) {
    Write-Error "Project path does not exist: $ProjectPath"
    exit 1
}

# Check if it's a Unity project
$projectSettingsPath = Join-Path $ProjectPath "ProjectSettings"
if (-not (Test-Path $projectSettingsPath)) {
    Write-Error "Not a valid Unity project (ProjectSettings folder not found): $ProjectPath"
    exit 1
}

# Get project name from path
$projectName = Split-Path $ProjectPath -Leaf
$timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
$zipFileName = "${projectName}_${timestamp}.zip"
$zipFilePath = Join-Path $OutputPath $zipFileName

Write-Host "================================================" -ForegroundColor Cyan
Write-Host "Unity Project Zipper" -ForegroundColor Cyan
Write-Host "================================================" -ForegroundColor Cyan
Write-Host "Project: $projectName" -ForegroundColor Green
Write-Host "Source: $ProjectPath" -ForegroundColor Yellow
Write-Host "Output: $zipFilePath" -ForegroundColor Yellow
Write-Host ""

# Essential folders and files to include
$includePaths = @(
    "Assets",
    "ProjectSettings",
    "Packages"
)

# Folders to exclude (regenerated by Unity)
$excludeFolders = @(
    "Library",
    "Temp",
    "obj",
    "Logs",
    "UserSettings",
    ".vs",
    "Build",
    "Builds"
)

# Create temporary directory for staging
$tempDir = Join-Path $env:TEMP "UnityZip_$([Guid]::NewGuid().ToString())"
$stagingDir = Join-Path $tempDir $projectName
New-Item -ItemType Directory -Path $stagingDir -Force | Out-Null

Write-Host "Copying essential files..." -ForegroundColor Cyan

# Copy essential folders
foreach ($folder in $includePaths) {
    $sourcePath = Join-Path $ProjectPath $folder
    if (Test-Path $sourcePath) {
        $destPath = Join-Path $stagingDir $folder
        Write-Host "  Copying $folder..." -ForegroundColor Gray
        
        # Use robocopy for better performance and exclusion handling
        $excludeArgs = $excludeFolders | ForEach-Object { "/XD `"$_`"" }
        $robocopyCmd = "robocopy `"$sourcePath`" `"$destPath`" /E /NFL /NDL /NJH /NJS /NC /NS /NP $excludeArgs"
        Invoke-Expression $robocopyCmd | Out-Null
        
        # Robocopy exit codes: 0-7 are success, 8+ are errors
        if ($LASTEXITCODE -ge 8) {
            Write-Warning "Error copying $folder (exit code: $LASTEXITCODE)"
        }
    } else {
        Write-Warning "  Folder not found: $folder (skipping)"
    }
}

# Copy root-level Unity files
Write-Host "  Copying project files..." -ForegroundColor Gray
Get-ChildItem -Path $ProjectPath -File | Where-Object {
    $_.Extension -match '\.(sln|csproj|unity|gitignore|gitattributes)$'
} | ForEach-Object {
    Copy-Item $_.FullName -Destination $stagingDir -Force
}

# Create the zip file
Write-Host ""
Write-Host "Creating zip archive..." -ForegroundColor Cyan
try {
    # Remove existing zip if it exists
    if (Test-Path $zipFilePath) {
        Remove-Item $zipFilePath -Force
        Write-Host "  Removed existing zip file" -ForegroundColor Gray
    }
    
    # Create zip using .NET compression
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    [System.IO.Compression.ZipFile]::CreateFromDirectory($tempDir, $zipFilePath, 'Optimal', $false)
    
    Write-Host ""
    Write-Host "================================================" -ForegroundColor Green
    Write-Host "SUCCESS!" -ForegroundColor Green
    Write-Host "================================================" -ForegroundColor Green
    $zipSize = (Get-Item $zipFilePath).Length / 1MB
    Write-Host "Zip file created: $zipFilePath" -ForegroundColor Yellow
    Write-Host "Size: $([math]::Round($zipSize, 2)) MB" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "To use on another machine:" -ForegroundColor Cyan
    Write-Host "  1. Extract the zip file" -ForegroundColor Gray
    Write-Host "  2. Open the project in Unity Hub" -ForegroundColor Gray
    Write-Host "  3. Unity will regenerate Library and other folders" -ForegroundColor Gray
    Write-Host "================================================" -ForegroundColor Green
}
catch {
    Write-Error "Failed to create zip file: $_"
    exit 1
}
finally {
    # Clean up temporary directory
    if (Test-Path $tempDir) {
        Remove-Item $tempDir -Recurse -Force
    }
}
